type: object
properties:
  id:
    type: integer
    format: int32
  code:
    type: string
    nullable: true
  name:
    type: string
    nullable: true
  fullName:
    type: string
    nullable: true
  specification:
    type: string
    nullable: true
  unitMeasure:
    type: string
    nullable: true
  unitMeasureAbbreviation:
    type: string
    nullable: true
  quantity:
    type: number
    format: double
  costAmountWithoutVAT:
    type: number
    format: double
  costAmountWithVAT:
    type: number
    format: double
  costAmountCurrency:
    type: number
    format: double
  salePrice:
    type: number
    format: double
  salePriceAmount:
    type: number
    format: double
additionalProperties: false

