type: object
properties:
  id:
    type: string
    format: uuid
  hasMore:
    type: boolean
  data:
    type: array
    items:
      $ref: "#/components/schemas/ProductsBalancesShortDataRow"
    nullable: true
additionalProperties: false

