/directories/products/{code}:
  get:
    tags: [Products]
    summary: Get product by code
    operationId: Products_Get
    parameters:
      - name: code
        in: path
        required: true
        schema:
          type: string
        description: Product code
    responses:
      '200':
        description: Product fetched successfully
        content:
          application/json:
            schema:
              $ref: ../../components/schemas/directories/Product.yaml
      '401':
        $ref: ../../components/responses/Unauthorized.yaml
      '403':
        $ref: ../../components/responses/Forbidden.yaml
      '404':
        $ref: ../../components/responses/NotFound.yaml
      '405':
        $ref: ../../components/responses/MethodNotAllowed.yaml
      '429':
        $ref: ../../components/responses/TooManyRequests.yaml
      '500':
        $ref: ../../components/responses/InternalError.yaml
      '503':
        $ref: ../../components/responses/ServiceUnavailable.yaml
      '200':
        description: Product updated successfully
        content:
          application/json:
            schema:
              $ref: ../../components/schemas/directories/Product.yaml
      '400':
        $ref: ../../components/responses/BadRequest.yaml
      '401':
        $ref: ../../components/responses/Unauthorized.yaml
      '403':
        $ref: ../../components/responses/Forbidden.yaml
      '404':
        $ref: ../../components/responses/NotFound.yaml
      '405':
        $ref: ../../components/responses/MethodNotAllowed.yaml
      '409':
        $ref: ../../components/responses/Conflict.yaml
      '429':
        $ref: ../../components/responses/TooManyRequests.yaml
      '500':
        $ref: ../../components/responses/InternalError.yaml
      '503':
        $ref: ../../components/responses/ServiceUnavailable.yaml
      '200':
        description: Product deleted successfully
      '401':
        $ref: ../../components/responses/Unauthorized.yaml
      '403':
        $ref: ../../components/responses/Forbidden.yaml
      '404':
        $ref: ../../components/responses/NotFound.yaml
      '405':
        $ref: ../../components/responses/MethodNotAllowed.yaml
      '409':
        $ref: ../../components/responses/Conflict.yaml
      '429':
        $ref: ../../components/responses/TooManyRequests.yaml
      '500':
        $ref: ../../components/responses/InternalError.yaml
      '503':
        $ref: ../../components/responses/ServiceUnavailable.yaml
