/directories/productsgroups:
  get:
    tags: [ProductsGroups]
    responses:
      '200':
        description: OK
      '401':
        $ref: ../../components/responses/Unauthorized.yaml
      '201':
        description: Created
        content:
          application/json:
            schema:
              $ref: ../../components/schemas/directories/ProductsGroup.yaml
      '401':
        $ref: ../../components/responses/Unauthorized.yaml
/directories/productsgroups/{code}:
  get:
    tags: [ProductsGroups]
    parameters:
      - name: code
        in: path
        required: true
        schema:
          type: string
    responses:
      '200':
        description: OK
      '401':
        $ref: ../../components/responses/Unauthorized.yaml
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: ../../components/schemas/directories/ProductsGroup.yaml
      '401':
        $ref: ../../components/responses/Unauthorized.yaml
      '200':
        description: OK
      '401':
        $ref: ../../components/responses/Unauthorized.yaml
