/documents/productsmovement:
  post:
    tags: [ProductsMovement]
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/documents/ProductsMovement.yaml
    responses:
      '201':
        description: Created
        content:
          application/json:
            schema:
              $ref: ../../components/schemas/documents/ProductsMovement.yaml
      '401':
        $ref: ../../openapi.yaml#/components/responses/Unauthorized
