type: object
properties:
  unitMeasure:
    type: string
    nullable: true
  abbreviation:
    type: string
    nullable: true
  barcode:
    type: string
    nullable: true
additionalProperties: false

